### ISSUE TITLE
allow any callable object, not just ::Function arguments

### ISSUE THREAD

**Issue by stevengj** [JuliaDiffEq/DASSL.jl#8]
On the [mailing list](https://groups.google.com/d/msg/julia-users/j8xEW9KEPxU/5XQIlRObBgAJ), someone was trying to call DASSL from Python via pyjulia.  This should work, but the Python function gets passed as a (callable) `::PyObject` argument, not a `::Function`.

It would be better to leave the arguments untyped rather than specify `::Function`, in order that any callable object can be passed.  Note that there is no performance advantage to declaring argument types; the main reason to declare arguments is to avoid method ambiguities.

**Comment by stevengj** [comment]
Note that using `Vector{T}` is also probably overtyped; you probably want `AbstractVector`.

**Comment by stevengj** [comment]
Also `::Int` is overtyped; you want `::Integer` (if you want to declare a type at all).  In general, the Julian approach is to make your code as generic as possible, within the bounds of correctness and clarity.

**Comment by ChrisRackauckas** [comment]
Those are all really good points.

**Comment by pwl** [comment]
Fixed with https://github.com/pwl/DASSL.jl/commit/838e07261066cd109d1e762d1c0b13e10736b002, hopefully I didn't miss a spot.  Sorry for these bugs, this package was written two years ago when I had little clue about Julia (REQUIRE still contains Julia 0.2:-)).  I also pushed a v0.0.5 tag.

**Comment by pwl** [comment]
So because we have to update METADATA anyway it's a good moment to move the package to JuliaDiffEq before doing that.

**Comment by stevengj** [comment]
Thanks!  (Note, by the way, that most Julia developers seem to be moving away from FactCheck and back to `Base.Test`, now that the latter has `@testset`; Base.Test has all of the functionality of FactCheck with a much more Julian syntax.)
